# Local docker-compose.yml file

services:
  db:
    image: postgres:18.0
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: book_social_network
    volumes:
      - db-data:/var/lib/postgresql/18/docker
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
    networks:
      - bsn
    restart: unless-stopped

volumes:
  db-data:
    driver: local

networks:
  bsn:
    driver: bridge
